name: 'Xquare deployment'
author: 'Xquare'
branding:
  icon: 'Xquare'
  color: 'Purple'

description: 'Tasks to deploy to xquare server'
inputs:
  environment:
    description: 'Environment classification for servers (prod/stag)' 
    required: true
  base_url:
    description: 'Base url of code'
    default: '.'
  config_file_path:
    description: 'Path of Xquare Config file'
    default: '.xquare/config.yaml'
  access_key:
    description: 'Access-key for authenticate to run action'
    required: true
  github_token:
    description: 'Github personal access token to repository dispatch. It should has a "repo" scope. Detail on [Github Document](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens)' 
    required: true
  yarn_docker_build:
    description: 'Boolean value indicating whether to use the "yarn docker build" command instead of the "docker build" command'
    default: false
  yarn_workspace:
    description: 'Workspace name to build docker image'
    required: false
  buildargs:
    description: 'Use buildargs when you want to pass a list of environment variables to docker as build-args'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install yq
      uses: mikefarah/yq@v4

    - name: Read config values
      uses: team-xquare/xquare-deployment-action/actions/read-config@master
      with:
        config_file_path: ${{ inputs.config_file_path }}
        environment: ${{ inputs.environment }}

    - name: Authenticate and get role-arn
      id: get-role-arn
      uses: team-xquare/xquare-deployment-action/actions/authenticate-and-get-arn@master
      with:
        access-key: ${{ inputs.access_key }}
        project-name: ${{ env.name }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.xquare_role_arn }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get ECR Repository name
      id: repository
      shell: bash
      run: echo "repository_name=${{ env.name }}-${{ env.type }}-${{ inputs.environment }}" >> $GITHUB_OUTPUT

    - name: Create ecr if not exists
      uses: team-xquare/xquare-deployment-action/actions/create-ecr@master
      with:
        repository_name: ${{ steps.repository.outputs.repository_name }}
        service_name: ${{ env.name }}
        service_type: ${{ env.type }}
        environment: ${{ inputs.environment }}
        github_token: ${{ inputs.github_token }}

    - name: Create domain if not exists
      if: ${{ env.domain }}
      uses: team-xquare/xquare-deployment-action/actions/create-domain@master
      with:
        domain: ${{ env.domain }}

    - name: Docker push
      uses: team-xquare/xquare-deployment-action/actions/docker-push@master
      with:
        registry_name: ${{ steps.ecr.outputs.registry }}
        repository_name: ${{ steps.repository.outputs.repository_name }}
        environment: ${{ inputs.environment }}
        base_url: ${{ inputs.base_url }}
        yarn_docker_build: ${{ inputs.yarn_docker_build }}
        yarn_workspace: ${{ inputs.yarn_workspace }}
        buildargs: ${{ inputs.buildargs }}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ inputs.github_token }}
        repository: team-xquare/xquare-gitops-repo
        event-type: update_config
        client-payload: |
          {
            "ref" : "${{ github.ref }}", 
            "image_tag" : "${{ steps.tag.outputs.version_tag }}",
            "service_name" : "${{ env.name }}",
            "service_prefix" : "${{ env.prefix }}",
            "service_domain" : "${{ env.domain }}",
            "service_type" : "${{ env.type }}",
            "service_port" : "${{ env.port }}",
            "environment" : "${{ inputs.environment }}"
          }
