name: 'Authenticate and get arn'

description: 'Verify access-key and return arn by server'
inputs:
  access_key:
    description: 'Access key to action'
    required: true
  project_name:
    description: 'Name of project'
    required: true
  project_type:
    description: 'Type of project'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Authenticate and get arn
      id: get-role-arn
      shell: bash
      run: |
        function urlencode() {
          local string="$1"
          local length="${#string}"

          for (( i = 0; i < length; i++ )); do
            local char="${string:i:1}"
            case $char in
              [a-zA-Z0-9.~_-]) printf "%s" "$char" ;;
              *) printf "%%%02X" "'$char"
            esac
          done
        }

        repository=${{ github.repository }}
        owner_name=${{ github.repository_owner }}

        url="https://prod-server.xquare.app/project-secret-manager/verify\
        ?access-key=$(urlencode ${{ inputs.access_key }})\
        &project-name=$(urlencode ${{ inputs.project_name }})\
        &project-type=$(urlencode ${{ inputs.project_type }})\
        &repository=$(urlencode $owner_name)%2F${repository#$owner_name/}"

        echo $url
        response=$(curl -X POST $url)
        if [[ "${response}" == "Unauthorized" ]]; then
          echo "Unauthorized: Invalid access key or no repository is registered running the action."
          exit 1
        fi

        echo "xquare_role_arn=${response}" >> $GITHUB_ENV
